const swaggerJsdoc = require('swagger-jsdoc');
const options = {
    basePath: '/api/',
    // List of files to be processed.
    apis: ['./app/routes/*.routes.ts', './app/models/*.dto.ts',],
    // You can also set globs for your apis
    // e.g. './routes/*.js'
    swaggerDefinition: {
        info: {
            description: 'Test API with autogenerated swagger doc',
            swagger: '2.0',
            title: 'Weather API',
            version: '1.0.0-dev',
        },
    },
};
const specs = swaggerJsdoc(options);
module.exports = specs;